# SVM - Email Spam Classifier
#### Libraries Used

In [1]:
from sklearn.metrics import precision_recall_fscore_support, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from IPython.display import clear_output
from sklearn.svm import SVC
import pandas as pd

#### Input File path

In [2]:
datasetPath = "spambase.data"

#### Headers and reading input data into pandas dataframe

In [3]:
headers = ["word_freq_make", "word_freq_address", "word_freq_all", "word_freq_3d", "word_freq_our", 
           "word_freq_over", "word_freq_remove", "word_freq_internet", "word_freq_order ", 
           "word_freq_mail", "word_freq_receive", "word_freq_will", "word_freq_people", 
           "word_freq_report", "word_freq_addresses", "word_freq_free", "word_freq_business", 
           "word_freq_email", "word_freq_you", "word_freq_credit", "word_freq_your", "word_freq_font", 
           "word_freq_000", "word_freq_money", "word_freq_hp", "word_freq_hpl", "word_freq_george", 
           "word_freq_650", "word_freq_lab", "word_freq_labs", "word_freq_telnet", "word_freq_857", 
           "word_freq_data", "word_freq_415", "word_freq_85", "word_freq_technology", "word_freq_1999",
           "word_freq_parts", "word_freq_pm", "word_freq_direct", "word_freq_cs", "word_freq_meeting", 
           "word_freq_original", "word_freq_project", "word_freq_re", "word_freq_edu", "word_freq_table", 
           "word_freq_conference", "char_freq_;", "char_freq_(", "char_freq_[", "char_freq_!", "char_freq_$", 
           "char_freq_#", "capital_run_length_average", "capital_run_length_longest", "capital_run_length_total", "class"]

df = pd.read_csv(datasetPath, names = headers)
df

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_freq_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,char_freq_;,char_freq_(,char_freq_[,char_freq_!,char_freq_$,char_freq_#,capital_run_length_average,capital_run_length_longest,capital_run_length_total,class
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.000,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.010,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.000,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.000,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4596,0.31,0.00,0.62,0.0,0.00,0.31,0.00,0.00,0.00,0.00,...,0.000,0.232,0.0,0.000,0.000,0.000,1.142,3,88,0
4597,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.353,0.000,0.000,1.555,4,14,0
4598,0.30,0.00,0.30,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.102,0.718,0.0,0.000,0.000,0.000,1.404,6,118,0
4599,0.96,0.00,0.00,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.000,0.057,0.0,0.000,0.000,0.000,1.147,5,78,0
4600,0.00,0.00,0.65,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.125,0.000,0.000,1.250,5,40,0

#### General information about the dataframe

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 58 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   word_freq_make              4601 non-null   float64
 1   word_freq_address           4601 non-null   float64
 2   word_freq_all               4601 non-null   float64
 3   word_freq_3d                4601 non-null   float64
 4   word_freq_our               4601 non-null   float64
 5   word_freq_over              4601 non-null   float64
 6   word_freq_remove            4601 non-null   float64
 7   word_freq_internet          4601 non-null   float64
 8   word_freq_order             4601 non-null   float64
 9   word_freq_mail              4601 non-null   float64
 10  word_freq_receive           4601 non-null   float64
 11  word_freq_will              4601 non-null   float64
 12  word_freq_people            4601 non-null   float64
 13  word_freq_report            4601 non-null   float64
 14  word_freq_addresses         4601 non-null   float64
 15  word_freq_free              4601 non-null   float64
 16  word_freq_business          4601 non-null   float64
 17  word_freq_email             4601 non-null   float64
 18  word_freq_you               4601 non-null   float64
 19  word_freq_credit            4601 non-null   float64
 20  word_freq_your              4601 non-null   float64
 21  word_freq_font              4601 non-null   float64
 22  word_freq_000               4601 non-null   float64
 23  word_freq_money             4601 non-null   float64
 24  word_freq_hp                4601 non-null   float64
 25  word_freq_hpl               4601 non-null   float64
 26  word_freq_george            4601 non-null   float64
 27  word_freq_650               4601 non-null   float64
 28  word_freq_lab               4601 non-null   float64
 29  word_freq_labs              4601 non-null   float64
 30  word_freq_telnet            4601 non-null   float64
 31  word_freq_857               4601 non-null   float64
 32  word_freq_data              4601 non-null   float64
 33  word_freq_415               4601 non-null   float64
 34  word_freq_85                4601 non-null   float64
 35  word_freq_technology        4601 non-null   float64
 36  word_freq_1999              4601 non-null   float64
 37  word_freq_parts             4601 non-null   float64
 38  word_freq_pm                4601 non-null   float64
 39  word_freq_direct            4601 non-null   float64
 40  word_freq_cs                4601 non-null   float64
 41  word_freq_meeting           4601 non-null   float64
 42  word_freq_original          4601 non-null   float64
 43  word_freq_project           4601 non-null   float64
 44  word_freq_re                4601 non-null   float64
 45  word_freq_edu               4601 non-null   float64
 46  word_freq_table             4601 non-null   float64
 47  word_freq_conference        4601 non-null   float64
 48  char_freq_;                 4601 non-null   float64
 49  char_freq_(                 4601 non-null   float64
 50  char_freq_[                 4601 non-null   float64
 51  char_freq_!                 4601 non-null   float64
 52  char_freq_$                 4601 non-null   float64
 53  char_freq_#                 4601 non-null   float64
 54  capital_run_length_average  4601 non-null   float64
 55  capital_run_length_longest  4601 non-null   int64
 56  capital_run_length_total    4601 non-null   int64
 57  class                       4601 non-null   int64
dtypes: float64(55), int64(3)
memory usage: 2.0 MB

#### Below Code Generate descriptive statistics

In [5]:
df.describe()

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_freq_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,char_freq_;,char_freq_(,char_freq_[,char_freq_!,char_freq_$,char_freq_#,capital_run_length_average,capital_run_length_longest,capital_run_length_total,class
count,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,...,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000
mean,0.104553,0.213015,0.280656,0.065425,0.312223,0.095901,0.114208,0.105295,0.090067,0.239413,...,0.038575,0.139030,0.016976,0.269071,0.075811,0.044238,5.191515,52.172789,283.289285,0.394045
std,0.305358,1.290575,0.504143,1.395151,0.672513,0.273824,0.391441,0.401071,0.278616,0.644755,...,0.243471,0.270355,0.109394,0.815672,0.245882,0.429342,31.729449,194.891310,606.347851,0.488698
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.588000,6.000000,35.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.065000,0.000000,0.000000,0.000000,0.000000,2.276000,15.000000,95.000000,0.000000
75%,0.000000,0.000000,0.420000,0.000000,0.380000,0.000000,0.000000,0.000000,0.000000,0.160000,...,0.000000,0.188000,0.000000,0.315000,0.052000,0.000000,3.706000,43.000000,266.000000,1.000000
max,4.540000,14.280000,5.100000,42.810000,10.000000,5.880000,7.270000,11.110000,5.260000,18.180000,...,4.385000,9.752000,4.081000,32.478000,6.003000,19.829000,1102.500000,9989.000000,15841.000000,1.000000

#### Seperating the label (class) column for training

In [6]:
data = df.drop(["class"], axis='columns')  #Stores the data except the last label (class)
label = df.iloc[:,-1]                      #Stores the label (class) column

#### Pre-processing data with StandardScaler for better training and 
#### Splitting the input data into 70% training and 30% testing sets

In [7]:
data = StandardScaler().fit_transform(data)
x_train, x_test, y_train, y_test = train_test_split(data, label, test_size = 0.3, random_state = 3)
print("Y_Train mean:", y_train.mean())
print("Y_Test mean", y_test.mean())

Y_Train mean: 0.3944099378881988
Y_Test mean 0.3931933381607531

#### Set of all C-Values and Kernals that are used

In [8]:
CValues = [0.0005, 0.0001, 0.005, 0.001, 0.05, 0.01, 0.5, 0.1, 1, 5, 10, 50, 100, 500, 1000, 5000]
kernals = ["linear", "poly", "rbf"]

#### Training, testing and printing results

In [9]:
result = pd.DataFrame(columns=["C_Value", "Linear_Train", "Linear_Test", "Poly_Train", "Poly_Test", "RBF_Train", "RBF_Test"])
for cval in CValues:
    accuracies = []
    for ker in kernals:
        #print("Starting")
        #print("C-Value:", cval)
        #print("Kernal:", ker)
        classifier = SVC(C=cval, kernel=ker , max_iter=1e8)
        classifier.fit(x_train, y_train)
        y_pred_train = classifier.predict(x_train)
        y_pred_test = classifier.predict(x_test)
        accuracies.append(accuracy_score(y_train, y_pred_train))
        accuracies.append(accuracy_score(y_test, y_pred_test))
        #print("Done")
        #print()

    result = result.append({'C_Value': cval, "Linear_Train": accuracies[0], "Linear_Test": accuracies[1], 
                          "Poly_Train": accuracies[2], "Poly_Test": accuracies[3],
                          "RBF_Train": accuracies[4], "RBF_Test": accuracies[5]}, ignore_index = True)
    clear_output(wait = True)
    display(result)

,C_Value,Linear_Train,Linear_Test,Poly_Train,Poly_Test,RBF_Train,RBF_Test
0,0.0005,0.863354,0.847212,0.610559,0.608979,0.605590,0.606807
1,0.0001,0.728882,0.713251,0.607453,0.608255,0.605590,0.606807
2,0.0050,0.912112,0.904417,0.617081,0.615496,0.605590,0.606807
3,0.0010,0.885714,0.880521,0.612112,0.609703,0.605590,0.606807
4,0.0500,0.927640,0.920348,0.677329,0.666908,0.890683,0.888487
5,0.0100,0.918012,0.912382,0.633540,0.623461,0.722981,0.690080
6,0.5000,0.929814,0.921796,0.760248,0.725561,0.937578,0.929761
7,0.1000,0.929193,0.922520,0.702484,0.688631,0.911491,0.909486
8,1.0000,0.931056,0.924692,0.793789,0.753802,0.946584,0.940623
9,5.0000,0.932609,0.922520,0.865217,0.813179,0.959938,0.942795
10,10.0000,0.932919,0.923244,0.893168,0.841419,0.967702,0.937002
11,50.0000,0.933851,0.924692,0.950000,0.900072,0.981056,0.931933
12,100.0000,0.933540,0.925416,0.963043,0.916003,0.985714,0.929761
13,500.0000,0.934472,0.921796,0.981988,0.917451,0.992547,0.926140
14,1000.0000,0.933540,0.917451,0.986646,0.918175,0.993789,0.923244
15,5000.0000,0.930435,0.916003,0.993168,0.921796,0.995963,0.905141

In [10]:
result.style.highlight_max(subset = ['Linear_Test', 'Poly_Test', 'RBF_Test'], color = 'lightgreen', axis = 0)